name: educore

services:
  config-server:
    container_name: educore-config-server

    build:
      context: ./infrastructure/config-server
      dockerfile: Dockerfile

    ports:
      - "8888:8888"

    environment:
      SPRING_PROFILES_ACTIVE: native
      SERVER_PORT: 8888

      # Đọc file config từ thư mục được mount
      CONFIG_SEARCH_LOCATIONS: file:/configurations

      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=75.0
        -XX:+ExitOnOutOfMemoryError

    volumes:
      - ./infrastructure/config-server/src/main/resources/configurations:/configurations:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8888/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    restart: unless-stopped

    networks:
      - educore-network

  discovery-service:
    build:
      context: ./infrastructure/discovery-service
      dockerfile: Dockerfile

    container_name: educore-discovery-service

    ports:
      - "8761:8761"

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SERVER_PORT: 8761

      # Ghi đè localhost bằng service name trong Docker
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery-service

    depends_on:
      config-server:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8761/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    restart: unless-stopped

    networks:
      - educore-network

  api-gateway:
    container_name: educore-api-gateway

    build:
      context: ./infrastructure/api-gateway
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: dev
      SERVER_PORT: 8080

      # Container gọi Config Server bằng service name
      CONFIG_SERVER_URL: http://config-server:8888

      # Container gọi Eureka bằng service name
      EUREKA_SERVER_URL: http://discovery-service:8761/eureka/

      # Trong Docker có thể đăng ký bằng container IP
      EUREKA_PREFER_IP_ADDRESS: "true"

      HEALTH_SHOW_DETAILS: never

      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=75.0
        -XX:+ExitOnOutOfMemoryError

    depends_on:
      config-server:
        condition: service_healthy

      discovery-service:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    restart: unless-stopped

    networks:
      - educore-network

  postgres:
    image: postgres:17-alpine
    container_name: educore-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: lehonganh
      POSTGRES_PASSWORD: ${DB_PASSWORD:-lehonganh}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./script/postgres/init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U lehonganh -d postgres"
        ]
      interval: 10s
      timeout: 5s
      retries: 10

    networks:
      - educore-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.7.0
    container_name: educore-keycloak
    restart: unless-stopped

    command:
      - start-dev

    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KEYCLOAK_ADMIN_USERNAME:-admin}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}

      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: lehonganh
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD:-lehonganh}

      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: http://localhost:9090

      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"

    ports:
      - "9090:8080"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - educore-network

networks:
  educore-network:
    name: educore-network
    driver: bridge

volumes:
  postgres_data: