name: educore

services:
  config-server:
    container_name: educore-config-server

    build:
      context: ./config-server
      dockerfile: Dockerfile

    ports:
      - "8888:8888"

    environment:
      SPRING_PROFILES_ACTIVE: native
      SERVER_PORT: 8888

      # Đọc file config từ thư mục được mount
      CONFIG_SEARCH_LOCATIONS: file:/configurations

      JAVA_OPTS: >-
        -XX:MaxRAMPercentage=75.0
        -XX:+ExitOnOutOfMemoryError

    volumes:
      - ./config-server/src/main/resources/configurations:/configurations:ro

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- http://localhost:8888/actuator/health | grep -q '\"status\":\"UP\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    restart: unless-stopped

    networks:
      - educore-network

  discovery-service:
    build:
      context: ./discovery-service

    container_name: educore-discovery-service

    ports:
      - "8761:8761"

    environment:
      SPRING_PROFILES_ACTIVE: dev

      SERVER_PORT: 8761

      # Ghi đè localhost bằng service name trong Docker
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_HOSTNAME: discovery-service

    depends_on:
      config-server:
        condition: service_healthy

    networks:
      - educore-network

networks:
  educore-network:
    name: educore-network
    driver: bridge